[SERVICE]
    Flush        5
    Daemon       Off
    Log_Level    warn
    Parsers_File /fluent-bit/etc/parsers.conf

[INPUT]
    Name              tail
    Tag               docker.*
    Path              /var/lib/docker/containers/*/*.log
    Parser            docker
    DB                /tmp/flb.db
    Buffer_Chunk_Size 32KB
    Buffer_Max_Size   64KB
    Refresh_Interval  10

[FILTER]
    Name         lua
    Match        docker.*
    Script       /fluent-bit/etc/level.lua
    Call         extract_level

[OUTPUT]
    Name         loki
    Match        docker.*
    Host         loki
    Port         3100
    Labels       job=docker
    Label_Keys   $level
    Line_Format  json
    Auto_Kubernetes_Labels off
